project:
  type: website
  output-dir: _site

website:
  title: "DSCI 532 Projects 2026"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/UBC-MDS/DSCI_532-projects

  repo-url: https://github.com/UBC-MDS/DSCI_532-projects
  repo-actions: [source]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
